version: "3.7"

services:
  frontend:
    build:
       context: ./bookmyshow-app
       dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
