version: "3.7"

services:
  frontend:
    build:
       context: ./bookmyshow-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
       environment:
      - NODE_ENV=production
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
