version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: bookmyshow-app/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
